name: Playwright Test
on: 
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        users: actions/checkout@v2
      - name: Say hello
        run: echo Hello